### PR TITLE
chore: add all-contributors

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Comment by nickserv** [comment]
Seems like this may need to have master merged/rebased after #2 was merged

**Comment by MichaelDeBoey** [comment]
Seems like @smeijer rewrote history on `main` branch or something, since I created this PR after #2 was merged

**Comment by smeijer** [comment]
Thanks. And apologies for the rebase :confused: I fucked while merging in your prettier commit.

**Comment by smeijer** [comment]
@all-contributors please add @MichaelDeBoey for docs

**Comment by smeijer** [comment]
@all-contributors please add @nickmccurdy for ideas

**Comment by smeijer** [comment]
@all-contributors please add @MichaelDeBoey for infra

**Pull request merged**
